---
- name: install riak
  apt: name={{ riak_package }} state=present
  when: riak_custom_package == False

- name: install riak custom
  command: dpkg --skip-same-version -i {{ riak_package }}
  register: dpkg_result
  changed_when: dpkg_result.stdout.startswith('Selecting')
  when: riak_custom_package != False

- name: set the riak ulimit
  copy: src=etc_default_riak_ulimit dest=/etc/default/riak owner=riak group=riak

